image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build:
  tags:
    - privileged
  services:
    - docker:dind
  before_script:
    - apt-get install docker
    - docker info
  image: maven:latest
  script:
    - ls -l