image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build:
  tags:
    - privileged
  services:
    - docker:dind
  before_script:
    - docker login -u oswald -p $CI_JOB_TOKEN docker.0x09.de
  image: krishofmans/gitlab-dind-maven:latest
  script:
    - mvn clean install
    - mvn deploy
